extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_Tree_lights;
extern Lights1 bob_dl_Wall_lights;
extern Lights1 bob_dl_Floor_lights;
extern Lights1 bob_dl_deathplane_lights;
extern u8 bob_dl_DarkOak_ci4[];
extern u8 bob_dl_DarkOak_pal_rgba16[];
extern u8 bob_dl_walls_ci8[];
extern u8 bob_dl_walls_pal_rgba16[];
extern u8 bob_dl_roof_ci8[];
extern u8 bob_dl_roof_pal_rgba16[];
extern u8 bob_dl_Woodthing_ci8[];
extern u8 bob_dl_Woodthing_pal_rgba16[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[833];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_1[249];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_2[52];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Cube_mesh_layer_4_vtx_cull[8];
extern Vtx bob_dl_Cube_mesh_layer_4_vtx_0[116];
extern Gfx bob_dl_Cube_mesh_layer_4_tri_0[];
extern Vtx bob_dl_deathplane_mesh_layer_5_vtx_cull[8];
extern Vtx bob_dl_deathplane_mesh_layer_5_vtx_0[4];
extern Gfx bob_dl_deathplane_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Roofs_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Roofs_mesh_layer_1_vtx_0[128];
extern Gfx bob_dl_Roofs_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_Tree[];
extern Gfx mat_revert_bob_dl_Tree[];
extern Gfx mat_bob_dl_Wall[];
extern Gfx mat_revert_bob_dl_Wall[];
extern Gfx mat_bob_dl_Floor[];
extern Gfx mat_revert_bob_dl_Floor[];
extern Gfx mat_bob_dl_Fence[];
extern Gfx mat_revert_bob_dl_Fence[];
extern Gfx mat_bob_dl_deathplane[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
extern Gfx bob_dl_Cube_mesh_layer_4[];
extern Gfx bob_dl_deathplane_mesh_layer_5[];
extern Gfx bob_dl_Roofs_mesh_layer_1[];
