extern const GeoLayout bounce_shroom_geo[];
extern Lights1 bounce_shroom_Base_lights;
extern Lights1 bounce_shroom_Top_lights;
extern u8 bounce_shroom_ShroomBase_ci4[];
extern u8 bounce_shroom_ShroomBase_pal_rgba16[];
extern u8 bounce_shroom_finalbossred_ci8[];
extern u8 bounce_shroom_finalbossred_pal_rgba16[];
extern Vtx bounce_shroom_Circle_mesh_layer_1_vtx_0[122];
extern Gfx bounce_shroom_Circle_mesh_layer_1_tri_0[];
extern Vtx bounce_shroom_Circle_mesh_layer_1_vtx_1[122];
extern Gfx bounce_shroom_Circle_mesh_layer_1_tri_1[];
extern Gfx mat_bounce_shroom_Base[];
extern Gfx mat_revert_bounce_shroom_Base[];
extern Gfx mat_bounce_shroom_Top[];
extern Gfx mat_revert_bounce_shroom_Top[];
extern Gfx bounce_shroom_Circle_mesh_layer_1[];
