extern const GeoLayout pss_area_1_geo[];
extern const GeoLayout pss_area_1[];
extern const Collision pss_area_1_collision[];
extern const MacroObject pss_area_1_macro_objs[];
extern Lights1 pss_dl_Material_lights;
extern Lights1 pss_dl_f3dlite_material_002_lights;
extern Lights1 pss_dl_f3dlite_material_lights;
extern u8 pss_dl_inside_castle_textures_04000_rgba16_rgba16[];
extern u8 pss_dl_inside_castle_textures_05000_rgba16_ci4[];
extern u8 pss_dl_inside_castle_textures_05000_rgba16_pal_rgba16[];
extern Vtx pss_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx pss_dl_Cube_mesh_layer_1_vtx_0[146];
extern Gfx pss_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx pss_dl_Cube_mesh_layer_1_vtx_1[21];
extern Gfx pss_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx pss_dl_Cube_mesh_layer_1_vtx_2[23];
extern Gfx pss_dl_Cube_mesh_layer_1_tri_2[];
extern Gfx mat_pss_dl_Material[];
extern Gfx mat_pss_dl_f3dlite_material_002[];
extern Gfx mat_pss_dl_f3dlite_material[];
extern Gfx mat_revert_pss_dl_f3dlite_material[];
extern Gfx pss_dl_Cube_mesh_layer_1[];
